#:schema node_modules/wrangler/config-schema.json
name = "obsidian-docs"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]


[observability]
enabled = true

[[r2_buckets]]
binding = "OBSIDIAN_BUCKET" 
bucket_name = "obsidian"
preview_bucket_name = "obsidian"

[[routes]]
pattern = "obsidi.soestin.nl"
custom_domain = true
